spring:
  application:
    name: reactive-exchange-converter
  profiles:
    active: "${ACTIVE_PROFILE:dev}"
  cache:
    type: redis
    cache-names: redis-cache
    redis:
      time-to-live: 5m
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}